### ISSUE TITLE
Issue checking Convergence.thy in Isabelle2018

### ISSUE THREAD

**Issue by heidihoward** [trvedata/crdt-isabelle#1]
I am trying to check the proof in [src/supplemental](https://github.com/trvedata/crdt-isabelle/tree/master/src/supplemental) using Isabelle2018.  

Isabelle is failing (for the first time I think) on the following line in [Convergence.thy](https://github.com/trvedata/crdt-isabelle/blob/master/src/supplemental/Convergence.thy):
```
definition apply_operations :: "'a list ⇒ 'b ⇀ 'b" where
  "apply_operations es ≡ foldl (op ⊳) Some (map interp es)"
```
Here's how it appears to me:

![Screen Shot 2019-04-29 at 15 26 23](https://user-images.githubusercontent.com/1835251/56902915-29785700-6a93-11e9-9325-0c4907108bb0.png)

As an Isabelle noob, it is likely an issue with my setup. Any suggestions?

**Comment by DePizzottri** [comment]
Replacement by `kleisli` seem to fix the problem

![image](https://user-images.githubusercontent.com/8318304/65677504-63598380-e05a-11e9-9820-569db1cc0e82.png)

**Comment by heidihoward** [comment]
Yes, that has fixed it for me. Thanks!
